kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: obc-meter
subjects:
  - kind: ServiceAccount
    name: obc-meter
    namespace: obc-meter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: obc-meter
